### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by noirmist** [acheong08/ChatGPT-Proxy-V4#22]
<img width="765" alt="Screen Shot 2023-03-29 at 2 22 34 AM" src="https://user-images.githubusercontent.com/8666069/228319381-6af9f949-4d21-430c-8ded-2b9cbf26711c.png">

When I trying to test ChatgptAPI, I've receive 404 error.

Error code from revChatGPT.V1

    python3 -m revChatGPT.V1                                                                                                                  

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT
        
    Type '!help' to show a full list of commands
    Press Esc followed by Enter or Alt+Enter to send a message.

    You: 
    hi

    Chatbot: 
    Traceback (most recent call last):
     File "/Users/noirmist/opt/anaconda3/envs/gpt/lib/python3.11/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
     File "/Users/noirmist/opt/anaconda3/envs/gpt/lib/python3.11/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
       conn.connect()
     File "/Users/noirmist/opt/anaconda3/envs/gpt/lib/python3.11/site-packages/urllib3/connection.py", line 369, in connect
    self._tunnel()
     File "/Users/noirmist/opt/anaconda3/envs/gpt/lib/python3.11/http/client.py", line 924, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
      OSError: Tunnel connection failed: 404 Not Found

I guess, I have issue to setting proxy server. Please share some information to setting the proxy.

**Comment by lp1014978271** [comment]
yes，I have similar question too,and my opint similar with you.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 03/29/2023 01:30 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [acheong08/ChatGPT-Proxy-V4] 404 Not Found (Issue #22) |

When I trying to test ChatgptAPI, I've receive 404 error.

Error code from revChatGPT.V1

python3 -m revChatGPT.V1                                                                                                                  

    ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
    Repo: github.com/acheong08/ChatGPT
    
Type '!help' to show a full list of commands
Press Esc followed by Enter or Alt+Enter to send a message.

You: 
hi

Chatbot: 
Traceback (most recent call last):
 File "/Users/noirmist/opt/anaconda3/envs/gpt/lib/python3.11/site-packages/urllib3/connectionpool.py", line 700, in urlopen
self._prepare_proxy(conn)
 File "/Users/noirmist/opt/anaconda3/envs/gpt/lib/python3.11/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
   conn.connect()
 File "/Users/noirmist/opt/anaconda3/envs/gpt/lib/python3.11/site-packages/urllib3/connection.py", line 369, in connect
self._tunnel()
 File "/Users/noirmist/opt/anaconda3/envs/gpt/lib/python3.11/http/client.py", line 924, in _tunnel
raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
  OSError: Tunnel connection failed: 404 Not Found


I guess, I have issue to setting proxy server. Please share some information to setting the proxy.

**Comment by acheong08** [comment]
Set as environment variable: `CHATGPT_BASE_URL`. Not proxy in config. That's different

**Comment by lp1014978271** [comment]
yes,ok



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Antonio ***@***.***> |
| Date | 03/29/2023 16:35 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [acheong08/ChatGPT-Proxy-V4] 404 Not Found (Issue #22) |

Set as environment variable: CHATGPT_BASE_URL. Not proxy in config. That's different

**Comment by Arche151** [comment]
> Set as environment variable: `CHATGPT_BASE_URL`. Not proxy in config. That's different

Hello, can you maybe elaborate a bit? I also get Error 404 and wasn't able to solve the issue because I don't understand what you meant by that :(
