### ISSUE TITLE
HTTPSConnectionPool(host='bypass.churchless.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 Not Found')))

### ISSUE THREAD

**Issue by Jirafey** [acheong08/ChatGPT-Proxy-V4#28]
C:\Users\jiraf\.config\revChatGPT>python -m revChatGPT.V1

        ChatGPT - A command-line interface to OpenAI's ChatGPT (https://chat.openai.com/chat)
        Repo: github.com/acheong08/ChatGPT

Type '!help' to show a full list of commands
←[1m←[93mPress Esc followed by Enter or Alt+Enter to send a message.←[0m

←[94m←[1mYou: ←[0m
hello

←[92m←[1mChatbot: ←[0m

Traceback (most recent call last):
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 371, in connect
    self._tunnel()
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 924, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 404 Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bypass.churchless.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 Not Found')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 962, in main
    for data in chatbot.ask(prompt):
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 443, in ask
    response = self.session.post(
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='bypass.churchless.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 Not Found')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 986, in <module>
    main(configure())
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\jiraf\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V1.py", line 972, in main
    raise error from e
revChatGPT.typings.CLIError: command line program unknown error

![image](https://user-images.githubusercontent.com/97115044/229288138-3b4354dd-69a0-4ab8-910a-458af497f046.png)

The chatbot works like a charm without a proxy, with proxy it begins to have problems, I look over the issues about CHATGPT_BASE_URL, it works but does not connect to proxy server on linux virtual machine.

**Comment by WuNein** [comment]
revChatGPT is default forward V1 chat to bypass.churchless.tech site. I hate this move!

**Comment by acheong08** [comment]
It seems you're trying to configure it as a proxy rather than with the environment variable.

Do `export CHATGPT_BASE_URL="https://HOST:PORT/api"`

**Comment by acheong08** [comment]
> revChatGPT is default forward V1 chat to bypass.churchless.tech site. I hate this move!

That is because chat.openai.com is inaccessible without a cloudflare bypass/solver
